[start]
command:/usr/local/etc/rc.d/os-tftp-proxy start
parameters:
type:script
message:starting tftp-proxy

[stop]
command:/usr/local/etc/rc.d/os-tftp-proxy stop
parameters:
type:script
message:stopping tftp-proxy

[restart]
command:/usr/local/etc/rc.d/os-tftp-proxy restart
parameters:
type:script
message:restarting tftp-proxy

[status]
command:/usr/local/etc/rc.d/os-tftp-proxy status; exit 0
parameters:
type:script_output
message:request tftp-proxy status
